### ISSUE TITLE
Documentation link 404 Not Found

### ISSUE THREAD

**Issue by jkeller13** [cocoadialog/cocoadialog#105]
The link to the documentation is no longer accessible.

https://cocoadialog.com/documentation

**Comment by omouse** [comment]
yep, just hit this broken link, I'm trying to make an edit to this answers on stackoverflow to point to the docs -> https://apple.stackexchange.com/a/73614/166989

**Comment by omouse** [comment]
looks like everything is hidden behind this link -> https://cocoadialog.com/v2/#

**Comment by markcarver** [comment]
As stated in #104, the link to the old documentation is present on the new landing page. There is nothing "hidden" about it, simply delayed in becoming visible for effect. I'll change the link in the README.md file to have a hash in front of it for now so it at least points to the landing page and doesn't receive a 404.

**Comment by omouse** [comment]
Awesome, thanks!

**Comment by jkeller13** [comment]
Completely missed that. Thank you!
