### ISSUE TITLE
cocoadialog.com web site is offline

### ISSUE THREAD

**Issue by ryandesign** [cocoadialog/cocoadialog#111]
Hello, I noticed that the [web site](https://cocoadialog.com) is offline.

> Error 522 Ray ID: 4a242e774c2d9b0e • 2019-02-01 11:47:38 UTC
> Connection timed out

**Comment by markcarver** [comment]
Yes, the server that this was on became compromised and I've been in the middle of rebuilding it (wasn't the only site affected). It should be back up shortly.

**Comment by markcarver** [comment]
https://cocoadialog.com is now back up
