### ISSUE TITLE
SourceForge project points to nonexistent web site

### ISSUE THREAD

**Issue by ryandesign** [cocoadialog/cocoadialog#112]
The [old SourceForge cocoadialog project's web site](http://cocoadialog.sourceforge.net) redirects to a [GitHub Pages web site](http://mstratman.github.com/cocoadialog/) that no longer exists. Can the configuration of the SourceForge project be updated to point to the [new web site](https://cocoadialog.com)?

**Comment by mstratman** [comment]
Thanks for the heads-up. I've updated the links.
