### ISSUE TITLE
Webpage is down

### ISSUE THREAD

**Issue by fauxserve** [cocoadialog/cocoadialog#118]
![Screen Shot 2021-11-17 at 2 11 34 PM](https://user-images.githubusercontent.com/15825721/142290915-5b8a91ed-4416-4a25-bd0c-ab062e822771.png)

Trying to access [cocoadialog.com](https://cocoadialog.com) results in a Cloudflare error page.

**Comment by tallfunnyjew** [comment]
Sure enough. Seems to have gone bye-bye, although the Github repo is still there. Odd.

**Comment by mstratman** [comment]
Closing since there's no plans to bring the site back. Instead I just updated the readme to point to the repo.
https://github.com/cocoadialog/cocoadialog/commit/1207409e42ffd8412eeea75f77f3e27dbbb65753
