### ISSUE TITLE
Transfer to organization

### ISSUE THREAD

**Issue by markcarver** [cocoadialog/cocoadialog#89]
@mstratman, I'd like to standardize some of the setup (mostly around documentation and issues) and I think it would make more sense to move this to an organization (so I can help manage the settings for the repo).

I'd like to transfer it to https://github.com/unicorn-fail if that's ok?

This is where https://github.com/unicorn-fail/node-cocoadialog lives now.

I've gone ahead and created a `cocoadialog` team and invited you to it. This should allow you to transfer and keep full existing perms.

If you're not comfortable with this org, can you create one specifically for `cocoadialog` then?

**Comment by markcarver** [comment]
@mstratman any feedback on this?

Specifically (soon), I will need to change the docs from the `gh-pages` branch to a `docs` subfolder.

Eventually, I would also like to create services/webhooks so I can start adding proper testing and other CI stuff.

**Comment by mstratman** [comment]
Hey @markcarver . Sorry I missed this.  Seems like a great idea. I'll see about transferring it now.

**Comment by mstratman** [comment]
Ok, I put it here: https://github.com/cocoadialog/cocoadialog

You're an owner of the org with full access, so feel free to do as you'd like, including transfer it over to the other org you linked above if you really want to. I just wasn't sure what it was and don't have time to look into it at the moment

Thanks for keeping on top of this!

**Comment by markcarver** [comment]
No problem, thanks! 😄 

I went ahead and transfered https://github.com/cocoadialog/node-cocoadialog to this new org as well just to keep it all together.
